"""
models.py

Common data models used by the
Taksa Market Intelligence Agent.

Author : Madhu
Version : 1.0
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Optional


###############################################################################
# ENUMS
###############################################################################

class EventType(str, Enum):
    """Business event categories."""

    EXPANSION = "Expansion"
    INVESTMENT = "Investment"
    PARTNERSHIP = "Partnership"
    ACQUISITION = "Acquisition"
    PRODUCT_LAUNCH = "Product Launch"
    CUSTOMER_WIN = "Customer Win"
    CUSTOMER_LOSS = "Customer Loss"
    FACTORY = "Factory"
    HIRING = "Hiring"
    LAYOFF = "Layoff"
    LEGAL = "Legal"
    FINANCIAL = "Financial"
    SUPPLY_CHAIN = "Supply Chain"
    OTHER = "Other"


###############################################################################

class Importance(str, Enum):
    """Business importance."""

    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


###############################################################################

class Sentiment(str, Enum):
    """Overall sentiment."""

    POSITIVE = "Positive"
    NEGATIVE = "Negative"
    NEUTRAL = "Neutral"
    MIXED = "Mixed"


###############################################################################

class RiskSeverity(str, Enum):
    """Risk severity."""

    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


###############################################################################

class Priority(str, Enum):
    """Recommendation priority."""

    P1 = "Critical"

    P2 = "High"

    P3 = "Medium"

    P4 = "Low"


###############################################################################

class SourceType(str, Enum):
    """Source of the information."""

    GOOGLE_NEWS = "Google News"

    NEWS_API = "News API"

    COMPANY_WEBSITE = "Company Website"

    PRESS_RELEASE = "Press Release"

    OTHER = "Other"


###############################################################################
# DATA MODELS
###############################################################################

@dataclass
class SourceArticle:
    """
    Original article used by the AI.
    """

    company: str

    title: str

    source: str

    url: str

    published: datetime

    summary: str = ""

    keyword: str = ""


###############################################################################

@dataclass
class MarketEvent:
    """
    Important business event detected by the AI.
    """

    company: str

    title: str

    summary: str

    event_type: EventType

    importance: Importance

    business_impact: str
    
    source: str

    url: str

    published: datetime

    sentiment: Sentiment = Sentiment.NEUTRAL

    confidence: float = 0.0


###############################################################################

@dataclass
class Risk:
    """
    Business risk identified by the AI.
    """

    company: str

    description: str

    severity: RiskSeverity

    impact: str

    mitigation: str = ""

    confidence: float = 0.0


###############################################################################

@dataclass
class Recommendation:
    """
    Recommended business action.
    """

    priority: Priority

    recommendation: str

    rationale: str


###############################################################################

@dataclass
class ExecutiveSummary:
    """
    Executive summary generated by the AI.
    """

    overview: str

    sentiment: Sentiment = Sentiment.NEUTRAL

    confidence: float = 0.0


###############################################################################

@dataclass
class MarketIntelligenceReport:
    """
    Final report generated for one company.
    """

    company: str

    report_date: datetime

    executive_summary: ExecutiveSummary

    events: List[MarketEvent] = field(default_factory=list)

    risks: List[Risk] = field(default_factory=list)

    recommendations: List[Recommendation] = field(default_factory=list)

    sources: List[SourceArticle] = field(default_factory=list)


###############################################################################